In [1]:
import json
import pandas as pd
from pprint import pprint

In [2]:
# Load unlabbled corpus
df_unlablled = pd.read_csv('/home/ameyh/mental-health-comorbitidy-classification/data/test/silver_labels_gpt.csv')
print(f"Total unlablled corpus: {df_unlablled.shape}")
df_unlablled.head(1)

Total unlablled corpus: (7667, 12)

,index,text,subreddit,author,system_description,prompt,gpt_prediction,Mental Health Disorder,Name of Mental Health Disorder,DSM5 Rationale,silver_label,id
0,11,"i woke up very early, 2 am. i just came out of...",ForeverAlone,SixViking,You are a Psychology professor working in the ...,"Reddit Post: ""i woke up very early, 2 am. i ju...",Mental Health Disorder: Yes\nName of Mental He...,Yes,Major Depressive Disorder (MDD),The language used in the post indicates severa...,Depression,4JEVyZ

In [3]:
# Load test set
df_test = pd.read_csv('/home/ameyh/mental-health-comorbitidy-classification/data/test/full_test.csv')
print(f"Total test set (blind): {df_test.shape}")
df_test.head(1)

Total test set (blind): (2872, 7)

,id,title,selftext,labels,disorder,text,groundtruth_label
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression

In [4]:
mapping = json.load(open("/home/ameyh/mental-health-comorbitidy-classification/data/mappings/semantic-similarity-depression.json"))
print(f"Total mapping: {len(mapping)}")
pprint(mapping)

Total mapping: 2872
{'3zf986': [['NBV7BY', 0.660976231098175],
            ['4WH6NR', 0.6449497938156128],
            ['3MpoEm', 0.6357589960098267],
            ['4UUZ86', 0.6193178296089172],
            ['43x8aJ', 0.6063274145126343],
            ['xorcU5', 0.5969784259796143],
            ['YrVXRu', 0.5959591269493103],
            ['noYHmg', 0.5952088832855225],
            ['489p8S', 0.5915932655334473],
            ['3oy9Zt', 0.5890166759490967],
            ['44J6or', 0.58294677734375],
            ['4PL9dr', 0.5821625590324402],
            ['3HWqd2', 0.5807008743286133],
            ['3tBZbd', 0.5753974914550781],
            ['44GdU5', 0.5747628211975098],
            ['37C5kK', 0.5729663372039795],
            ['43rqkt', 0.5722278952598572],
            ['3r6KrN', 0.5708215832710266],
            ['omLtQm', 0.5663670301437378],
            ['32CxkC', 0.565447986125946],
            ['4VsXLZ', 0.56522136926651],
            ['355jG5', 0.5644267201423645],
            ['4Jo2Bs', 0.5640807151794434],
            ['WfkKBw', 0.5624306201934814],
            ['48GhoC', 0.5615618824958801],
            ['yM8TBS', 0.5615612864494324],
            ['5KuuR7', 0.5595810413360596],
            ['4LAyQ8', 0.5577110052108765],
            ['EPusaC', 0.5566978454589844],
            ['3xg3AN', 0.5551369190216064]],
 '3zilnq': [['NvUKZP', 0.765243649482727],
            ['nDfJgp', 0.7474141120910645],
            ['jmjCk2', 0.7416543960571289],
            ['eh2AcU', 0.7410233616828918],
            ['T6SL6i', 0.7399435043334961],
            ['3W9HLB', 0.7360173463821411],
            ['4MUJoM', 0.7336978912353516],
            ['3JXTTv', 0.7321593165397644],
            ['qAGdNU', 0.7282222509384155],
            ['3DY2Qk', 0.7264499664306641],
            ['dmCAST', 0.715705156326294],
            ['r559b7', 0.7145364284515381],
            ['3AwDPK', 0.7144320011138916],
            ['4Kx6SX', 0.7137973308563232],
            ['3XQZNy', 0.7122246026992798],
            ['3rywTN', 0.7113119959831238],
            ['sr5LU4', 0.7104451656341553],
            ['oYhXpY', 0.7099718451499939],
            ['8eTCUH', 0.7086390256881714],
            ['3Jn533', 0.7071306705474854],
            ['3P4zy8', 0.7065417766571045],
            ['3Hf33q', 0.7063332200050354],
            ['Dmpvw6', 0.7037225961685181],
            ['3XbeBw', 0.702972412109375],
            ['3akRNd', 0.7014584541320801],
            ['4KreW9', 0.6999584436416626],
            ['CoWbit', 0.6995863914489746],
            ['Et3CTF', 0.6991222500801086],
            ['3Z4bfa', 0.6984105110168457],
            ['3N9dXs', 0.6960397958755493]],
 '3zudje': [['pNoYzX', 0.6937789916992188],
            ['3avuSt', 0.6713535785675049],
            ['4CWnkG', 0.6459454894065857],
            ['3Tyjsr', 0.6444300413131714],
            ['4CEXAu', 0.6361309885978699],
            ['hNGvCc', 0.6357387900352478],
            ['rH9Ge7', 0.6193419694900513],
            ['42v7ZZ', 0.6103255748748779],
            ['3L9gyc', 0.6072448492050171],
            ['xAVHZy', 0.6048554182052612],
            ['6EgB4S', 0.6012340188026428],
            ['vQFpPp', 0.5978330969810486],
            ['4N7UWo', 0.5975055694580078],
            ['3CzxnM', 0.5961766242980957],
            ['4JmaVk', 0.5947882533073425],
            ['3sxinG', 0.5855266451835632],
            ['4KqtUE', 0.5834485292434692],
            ['4NRWy7', 0.5810235142707825],
            ['5kRj3u', 0.5775380730628967],
            ['HAQDhb', 0.572579026222229],
            ['3hsCU7', 0.5693476796150208],
            ['46kEXj', 0.5676224827766418],
            ['poFCeW', 0.5652555823326111],
            ['y32txx', 0.5620033740997314],
            ['CScodc', 0.5613890290260315],
            ['583woE', 0.5609636306762695],
            ['3qVjQe', 0.5560494661331177],
            ['3ZDkFS', 0.5549895167350769],
            ['3egL4n', 0.5499160885810852],
            ['4HWhbe', 0.549251914024353]],
 '3zwb7c': [['p9S4Gx', 0.7374522686004639],
            ['HAQDhb', 0.7278186082839966],
            ['4PCygE', 0.7103102207183838],
            ['fryZY3', 0.697981595993042],
            ['rH9Ge7', 0.693517804145813],
            ['7UywVH', 0.6884142160415649],
            ['3urjD6', 0.6794359683990479],
            ['qBamdm', 0.6791595220565796],
            ['3dnA9M', 0.6773026585578918],
            ['3dUo3q', 0.6746089458465576],
            ['4NRWy7', 0.6742967367172241],
            ['hYrnJo', 0.6702276468276978],
            ['3WB9Vi', 0.6701983213424683],
            ['jTZguX', 0.669490396976471],
            ['xxtHMz', 0.6661367416381836],
            ['3sY5qi', 0.6644924283027649],
            ['3azvuq', 0.6621686220169067],
            ['QXGk34', 0.6528289914131165],
            ['zFt5MY', 0.6527903079986572],
            ['pfYhsr', 0.6521986722946167],
            ['3Tyjsr', 0.6516430377960205],
            ['3yQDRb', 0.6505532264709473],
            ['3TKBmc', 0.6500866413116455],
            ['qNcbiv', 0.6485987901687622],
            ['3syuwt', 0.6474062204360962],
            ['3u3C4i', 0.6473309993743896],
            ['4GrgBa', 0.6469066143035889],
            ['4AZPsK', 0.6468645334243774],
            ['3P4zy8', 0.6446397304534912],
            ['sywFut', 0.6438894271850586]],
 '400qga': [['zFt5MY', 0.8029762506484985],
            ['xAVHZy', 0.7968978881835938],
            ['rH9Ge7', 0.7919586896896362],
            ['hNGvCc', 0.7899280786514282],
            ['4NRWy7', 0.7712950110435486],
            ['3yQDRb', 0.7588221430778503],
            ['CScodc', 0.7550095319747925],
            ['583woE', 0.7498014569282532],
            ['HAQDhb', 0.7477421760559082],
            ['3dnA9M', 0.7374647259712219],
            ['3TKBmc', 0.7339001893997192],
            ['48GhoC', 0.7327960729598999],
            ['4WgSnQ', 0.7326093316078186],
            ['3WB9Vi', 0.7306662797927856],
            ['4TTroA', 0.727962851524353],
            ['qwaf4A', 0.724684476852417],
            ['5kRj3u', 0.7232447862625122],
            ['4Rzkdv', 0.7231149077415466],
            ['3avuSt', 0.7176210880279541],
            ['3CzxnM', 0.7168382406234741],
            ['RixgMK', 0.7151685953140259],
            ['qBamdm', 0.7129184007644653],
            ['3sxinG', 0.7096676826477051],
            ['37RmBQ', 0.7070860862731934],
            ['Wm2Lye', 0.7068573236465454],
            ['y32txx', 0.7066177725791931],
            ['sywFut', 0.7060417532920837],
            ['4RqJgc', 0.7054719924926758],
            ['3UF2Hu', 0.7052751779556274],
            ['agWmNR', 0.7046215534210205]],
 '400zis': [['db9o8k', 0.5121092796325684],
            ['3Qxhpj', 0.5074663162231445],
            ['43x8aJ', 0.4760737717151642],
            ['4HWhbe', 0.46934974193573],
            ['3xg3AN', 0.45420601963996887],
            ['3p5xrx', 0.453491747379303],
            ['yM8TBS', 0.45226892828941345],
            ['3oy9Zt', 0.45023855566978455],
            ['3tBZbd', 0.4497792720794678],
            ['3XCWLf', 0.4486197233200073],
            ['MfnkGe', 0.4475424885749817],
            ['3dmiDh', 0.4471217393875122],
            ['46M6VM', 0.44176816940307617],
            ['39mu52', 0.439889132976532],
            ['5KuuR7', 0.43883413076400757],
            ['3z4jUU', 0.43731003999710083],
            ['sUcQ8J', 0.43369996547698975],
            ['ci963J', 0.4329913556575775],
            ['3xLSri', 0.43262696266174316],
            ['xorcU5', 0.4325007498264313],
            ['4axUN9', 0.43182605504989624],
            ['33rEAJ', 0.42953619360923767],
            ['3DLXGh', 0.4209293723106384],
            ['3CMrZa', 0.42052584886550903],
            ['NCkiZK', 0.41888493299484253],
            ['YrVXRu', 0.4172506034374237],
            ['3DQFwM', 0.4166087508201599],
            ['Rd6EzE', 0.4152235984802246],
            ['3cDVsy', 0.41458576917648315],
            ['NvUKZP', 0.4145069718360901]],
 '4017zq': [['4QRnqt', 0.7136027812957764],
            ['QKuCPT', 0.7072117328643799],
            ['qwaf4A', 0.7055234313011169],
            ['3v3Eje', 0.6943263411521912],
            ['y7BNim', 0.6925477385520935],
            ['YNxBgJ', 0.6878364086151123],
            ['3djvhF', 0.6839982867240906],
            ['485Zgw', 0.6812061667442322],
            ['35Ykof', 0.680962085723877],
            ['3syuwt', 0.6798770427703857],
            ['4X2ULq', 0.678716778755188],
            ['49F5SZ', 0.6765949726104736],
            ['DitgCR', 0.6688039302825928],
            ['4W82zb', 0.6626483201980591],
            ['3TN6EZ', 0.6568706035614014],
            ['38WgbJ', 0.6563509106636047],
            ['45QP9z', 0.6559618711471558],
            ['486dHi', 0.6503511667251587],
            ['4SXx6q', 0.6496888995170593],
            ['3LCJxU', 0.6468676328659058],
            ['3xAEvd', 0.6462152600288391],
            ['WNRv3k', 0.6456197500228882],
            ['3P46m3', 0.6453480124473572],
            ['4VyotB', 0.6447497606277466],
            ['Wm2Lye', 0.643323540687561],
            ['3akRNd', 0.641879677772522],
            ['3veHE7', 0.6407276391983032],
            ['qYX9mt', 0.6389894485473633],
            ['N4sr7P', 0.6380132436752319],
            ['3yAPib', 0.6373209357261658]],
 '402127': [['hNGvCc', 0.7725691795349121],
            ['3avuSt', 0.7257843017578125],
            ['zFt5MY', 0.7248377799987793],
            ['3CzxnM', 0.722882866859436],
            ['3Tyjsr', 0.7222158312797546],
            ['xAVHZy', 0.718660831451416],
            ['pNoYzX', 0.7180325984954834],
            ['RixgMK', 0.7159736752510071],
            ['CScodc', 0.7113533020019531],
            ['rH9Ge7', 0.7097076177597046],
            ['3qVjQe', 0.7091962099075317],
            ['4JmaVk', 0.7037397027015686],
            ['4CEXAu', 0.7024183869361877],
            ['3dUo3q', 0.6973209381103516],
            ['3L9gyc', 0.6944742798805237],
            ['4NRWy7', 0.6917924284934998],
            ['JaDKEu', 0.6853054761886597],
            ['3WB9Vi', 0.6828213930130005],
            ['mxKLvk', 0.681900143623352],
            ['3zBQaZ', 0.6798226833343506],
            ['3nvoGf', 0.679419219493866],
            ['4CWnkG', 0.679316520690918],
            ['bgwUJD', 0.679053783416748],
            ['3dnA9M', 0.6757189035415649],
            ['3Czs2j', 0.6748005747795105],
            ['eLNcar', 0.6733327507972717],
            ['583woE', 0.6730452179908752],
            ['qwaf4A', 0.6727213859558105],
            ['sywFut', 0.671795129776001],
            ['3yQDRb', 0.6644246578216553]],
 '40aael': [['4UH7m2', 0.7372092008590698],
            ['M8568G', 0.6981101036071777],
            ['WChjnE', 0.6979507207870483],
            ['32exSh', 0.6709016561508179],
            ['3YuhYv', 0.67037034034729],
            ['db9o8k', 0.6583049297332764],
            ['mcGukW', 0.6581500768661499],
            ['4TgeUz', 0.6572915315628052],
            ['TZzQb5', 0.6566289663314819],
            ['3kjaW3', 0.6526190042495728],
            ['3LXJYv', 0.650813102722168],
            ['3eMVX6', 0.6502850651741028],
            ['38HwLs', 0.6463279724121094],
            ['WggghM', 0.6459717750549316],
            ['4LJEyp', 0.6431616544723511],
            ['3Kz7cY', 0.6429842114448547],
            ['tDpn7g', 0.6403993368148804],
            ['Et3CTF', 0.6344634294509888],
            ['racAjz', 0.6316523551940918],
            ['MP6act', 0.6311134099960327],
            ['37RmBQ', 0.6301090717315674],
            ['3N9dXs', 0.6265057325363159],
            ['3UFaqe', 0.625640332698822],
            ['44KurG', 0.6252186894416809],
            ['33ubvX', 0.6228919625282288],
            ['4RqJgc', 0.6208328604698181],
            ['fryZY3', 0.6197148561477661],
            ['4MobKf', 0.6166031360626221],
            ['3pfDse', 0.616326630115509],
            ['3TvWxB', 0.6157795190811157]],
 '40axvg': [['3n3hJv', 0.7702602744102478],
            ['SMP3nS', 0.7681652307510376],
            ['4BdMtz', 0.7495118379592896],
            ['4UjUfi', 0.7382951378822327],
            ['3PLoWF', 0.7072184681892395],
            ['3Qnjzc', 0.7024948596954346],
            ['jgbQ4H', 0.6974225044250488],
            ['3Ldnau', 0.6724207401275635],
            ['aPG7bD', 0.668281078338623],
            ['noYHmg', 0.6589101552963257],
            ['3PEaYQ', 0.6524609327316284],
            ['3meeqU', 0.6520488262176514],
            ['mib8QD', 0.6507939100265503],
            ['EPusaC', 0.6439072489738464],
            ['ksQdMN', 0.6415213942527771],
            ['3zhFoA', 0.6407613158226013],
            ['4T4CXp', 0.6403687000274658],
            ['3fNNMW', 0.6393374800682068],
            ['4SaCvo', 0.6377291679382324],
            ['M9Qdo7', 0.6370437145233154],
            ['3TFFPj', 0.6332749128341675],
            ['qq4mtp', 0.6327400207519531],
            ['WBJ54f', 0.6324850916862488],
            ['cqKqSu', 0.6283469796180725],
            ['b56RAo', 0.6278393268585205],
            ['43x8aJ', 0.6272067427635193],
            ['4WL4U3', 0.6268596053123474],
            ['3DXKx8', 0.6262642741203308],
            ['49amvc', 0.6242169141769409],
            ['jmjCk2', 0.6217277646064758]],
 '40f9bq': [['3hYT95', 0.7479670643806458],
            ['4i5Nef', 0.6903457641601562],
            ['3B8q9X', 0.6843209862709045],
            ['Rfuqcw', 0.6648657917976379],
            ['4FDDx6', 0.6524049639701843],
            ['kDWszY', 0.6437132358551025],
            ['sywFut', 0.6408299803733826],
            ['HbZ9kf', 0.6376194357872009],
            ['3xJsML', 0.6277023553848267],
            ['zdiYfn', 0.6253646612167358],
            ['4TB6Rb', 0.623975396156311],
            ['3uGDfQ', 0.6211053729057312],
            ['3u69Dn', 0.6197584271430969],
            ['jmjCk2', 0.6162576675415039],
            ['3Cmt6D', 0.6104652285575867],
            ['3UF2Hu', 0.6075936555862427],
            ['38RgRk', 0.6069316267967224],
            ['3mXCcN', 0.605205237865448],
            ['3U7P7f', 0.6042847633361816],
            ['dowNiL', 0.6030149459838867],
            ['3F8Jhb', 0.601280927658081],
            ['32M6pH', 0.599208652973175],
            ['dmCAST', 0.5991601943969727],
            ['3tcqQn', 0.5988872647285461],
            ['33ZGyr', 0.5982362627983093],
            ['36Esc3', 0.598232090473175],
            ['3FcZLx', 0.5967898964881897],
            ['KQnnVc', 0.5967241525650024],
            ['4PXw9m', 0.5966407060623169],
            ['Xx4y9B', 0.5961874723434448]],
 '40j1r6': [['3QyFop', 0.7252817153930664],
            ['riTGxK', 0.7021809220314026],
            ['PURFuF', 0.7007685899734497],
            ['PU24zf', 0.6968010663986206],
            ['AP27XM', 0.6943970322608948],
            ['bcgPWM', 0.6904834508895874],
            ['MwtoZY', 0.6901242136955261],
            ['4QeVid', 0.6868185997009277],
            ['4RYW9n', 0.6763879656791687],
            ['3sT5jt', 0.6760833859443665],
            ['opJMCt', 0.6752015352249146],
            ['pHuiY5', 0.6719141602516174],
            ['5UgZWs', 0.6697813868522644],
            ['46Mrdz', 0.6695218086242676],
            ['4BZsCK', 0.6691057682037354],
            ['vtcydP', 0.6685861945152283],
            ['3DQFwM', 0.6666088104248047],
            ['xH9e25', 0.6649685502052307],
            ['3adaUJ', 0.6614776849746704],
            ['vBXhdU', 0.6595408916473389],
            ['3MrX8D', 0.6586987376213074],
            ['47E5RR', 0.6574356555938721],
            ['4Rzkdv', 0.6570079326629639],
            ['zKshpN', 0.6553778648376465],
            ['ftrybc', 0.6549912095069885],
            ['4PL9dr', 0.6548765897750854],
            ['qNcbiv', 0.654118537902832],
            ['3nMyQb', 0.6516459584236145],
            ['3tPqAE', 0.6506098508834839],
            ['V3ogDU', 0.6493828892707825]],
 '40j55i': [['3QyFop', 0.7182943820953369],
            ['PURFuF', 0.6965125799179077],
            ['riTGxK', 0.6962687969207764],
            ['PU24zf', 0.6911386251449585],
            ['bcgPWM', 0.686631977558136],
            ['AP27XM', 0.6835324764251709],
            ['4QeVid', 0.6794458031654358],
            ['MwtoZY', 0.6792777180671692],
            ['4RYW9n', 0.6718554496765137],
            ['4BZsCK', 0.6702051162719727],
            ['opJMCt', 0.6683213710784912],
            ['5UgZWs', 0.6673638820648193],
            ['3sT5jt', 0.6668559312820435],
            ['pHuiY5', 0.6662485003471375],
            ['3DQFwM', 0.663297176361084],
            ['vtcydP', 0.6627312898635864],
            ['xH9e25', 0.6618794202804565],
            ['46Mrdz', 0.6614780426025391],
            ['3MrX8D', 0.6534967422485352],
            ['3adaUJ', 0.6534068584442139],
            ['zKshpN', 0.6516780853271484],
            ['4Rzkdv', 0.6495774984359741],
            ['vBXhdU', 0.6493581533432007],
            ['4PL9dr', 0.6479635238647461],
            ['ftrybc', 0.6471186280250549],
            ['47E5RR', 0.6457716822624207],
            ['qNcbiv', 0.6440069675445557],
            ['4BLGrL', 0.6429154872894287],
            ['V3ogDU', 0.6427773833274841],
            ['3nMyQb', 0.6424582600593567]],
 '40kgfq': [['4A3WYF', 0.6831779479980469],
            ['3T3D54', 0.6655338406562805],
            ['3TFFPj', 0.6449593305587769],
            ['83kfYH', 0.6413915753364563],
            ['4Kx6SX', 0.6374571323394775],
            ['KPBuoA', 0.6338095664978027],
            ['7aD6he', 0.6334738731384277],
            ['zQZJ5V', 0.631606936454773],
            ['WBJ54f', 0.631308913230896],
            ['3jXhF6', 0.6300572156906128],
            ['4BdMtz', 0.6287409663200378],
            ['4Ucs5Q', 0.628160834312439],
            ['nDfJgp', 0.6271719932556152],
            ['3xLkCd', 0.6270740628242493],
            ['DTSCzC', 0.6269937753677368],
            ['jmjCk2', 0.6247856616973877],
            ['LmNLjv', 0.6213294267654419],
            ['39wztL', 0.6205695867538452],
            ['435Fao', 0.6166841387748718],
            ['4SaCvo', 0.6158336400985718],
            ['cqKqSu', 0.6154342889785767],
            ['pMQLHp', 0.6144672632217407],
            ['4UiLsP', 0.6084868907928467],
            ['3XbeBw', 0.6084275245666504],
            ['3Rzqw7', 0.6079127788543701],
            ['8iBWMq', 0.6065275073051453],
            ['4VQkwW', 0.6049017906188965],
            ['3JXTTv', 0.6039857864379883],
            ['3PEaYQ', 0.6029449105262756],
            ['4V5RtX', 0.6020116806030273]],
 '40lqwb': [['RHKc4C', 0.7572653889656067],
            ['mgvHc9', 0.7348262071609497],
            ['3KfmKB', 0.7348262071609497],
            ['4SdKvt', 0.7271794080734253],
            ['3VxQzd', 0.7102439999580383],
            ['3Z4bfa', 0.7050485610961914],
            ['3Hf33q', 0.6988013386726379],
            ['ZPZfKC', 0.6866893768310547],
            ['4QSbMM', 0.6797329783439636],
            ['36yLze', 0.674628496170044],
            ['EPXkMt', 0.6742503046989441],
            ['3N9dXs', 0.6702920198440552],
            ['jmjCk2', 0.6693871021270752],
            ['8eTCUH', 0.6618137359619141],
            ['49FrWN', 0.6603168845176697],
            ['vp9pK5', 0.6508298516273499],
            ['oPxcRf', 0.649916410446167],
            ['xFFbMu', 0.6470898389816284],
            ['Et3CTF', 0.647036075592041],
            ['4Vqp2d', 0.6447659730911255],
            ['qyfeps', 0.6445754170417786],
            ['4PL9dr', 0.6431876420974731],
            ['dmCAST', 0.6413170099258423],
            ['4H6SyB', 0.6410253047943115],
            ['4VcYp4', 0.6397530436515808],
            ['3P4zy8', 0.638443112373352],
            ['3mqTaU', 0.6377959251403809],
            ['QXGk34', 0.6356532573699951],
            ['3VFBMd', 0.635140061378479],
            ['govXa2', 0.6332642436027527]],
 '40r1cc': [['ukvbX3', 0.7669461965560913],
            ['4PpdCK', 0.7647074460983276],
            ['3yNZEw', 0.7646633386611938],
            ['MwtoZY', 0.7640972137451172],

In [5]:
assert len(mapping) == df_test.shape[0]

#### Get top-k exemplars for a particular datapoint in test set

In [6]:
sample_datapoint = df_test.sample()
sample_datapoint

,id,title,selftext,labels,disorder,text,groundtruth_label
2245,7m4m6j,My brother died and it hurts so much,My younger brother was found dead in his apart...,"[1, 0]",{'depressive_disorder'},My brother died and it hurts so much. My young...,Depression

In [7]:
exemplars = mapping[sample_datapoint.iloc[0]['id']]
pprint(exemplars)

[['rCn73f', 0.7188562154769897],
 ['3ybHCD', 0.7154527902603149],
 ['BKVBJK', 0.7026964426040649],
 ['4Fvdcu', 0.7014690637588501],
 ['3KrZay', 0.700445294380188],
 ['siihXv', 0.6891827583312988],
 ['3CzxnM', 0.6487476229667664],
 ['3dUzsu', 0.6467969417572021],
 ['WfkKBw', 0.6390045285224915],
 ['3NBxDC', 0.6388687491416931],
 ['KzmSLG', 0.6349929571151733],
 ['3LBG3Q', 0.6284743547439575],
 ['7UywVH', 0.6118215322494507],
 ['4DiPtP', 0.6038773059844971],
 ['xxtHMz', 0.6002994179725647],
 ['3hoNFK', 0.5984659194946289],
 ['4RM53c', 0.5964802503585815],
 ['eLNcar', 0.5786051154136658],
 ['3dUo3q', 0.5779073238372803],
 ['4JmaVk', 0.5759375095367432],
 ['wGqbmx', 0.5753626823425293],
 ['3VimP8', 0.5749728679656982],
 ['37Rpxx', 0.5731668472290039],
 ['pfYhsr', 0.5695798397064209],
 ['HAQDhb', 0.567937970161438],
 ['3KdbHZ', 0.5667355060577393],
 ['3aKuMw', 0.5627630352973938],
 ['3si6rs', 0.5580594539642334],
 ['JuEJqL', 0.5569185614585876],
 ['dSc4hS', 0.5567352771759033]]

In [8]:
exemplar_ids = [i[0] for i in exemplars]
exemplar_df = df_unlablled[df_unlablled['id'].isin(exemplar_ids)]
print(exemplar_df.shape)
exemplar_df.head(1)

(30, 12)

,index,text,subreddit,author,system_description,prompt,gpt_prediction,Mental Health Disorder,Name of Mental Health Disorder,DSM5 Rationale,silver_label,id
9,77,"hi there, i am currently at a very stressful t...",depression_help,Vikturus22,You are a Psychology professor working in the ...,"Reddit Post: ""hi there, i am currently at a ve...",Mental Health Disorder: Yes\n\nName of Mental ...,Yes,Major Depressive Disorder,The language and content of the Reddit post in...,Depression,3NBxDC

### Add exemplar as a column in df_test

In [10]:
df_test['exemplars_semantic_similarity'] = None
df_test['mapping_semantic_similarity'] = None
topk = 10

for i in range(df_test.shape[0]):
    exemplars = mapping[df_test.iloc[i]['id']]
    exemplar_ids = [i[0] for i in exemplars][:topk]
    exemplar_df = df_unlablled[df_unlablled['id'].isin(exemplar_ids)]
    exemplar_posts = exemplar_df['text'].values.tolist()
    df_test.at[i, 'exemplars_semantic_similarity'] = json.dumps(exemplar_posts)
    df_test.at[i, 'mapping_semantic_similarity'] = json.dumps(exemplars)

In [11]:
df_test.head(1)

,id,title,selftext,labels,disorder,text,groundtruth_label,exemplars_semantic_similarity,mapping_semantic_similarity
0,8es6qn,I cut myself for the first time in a year toda...,... and hated that I still loved it. The burni...,"[1, 0]",{'depressive_disorder'},I cut myself for the first time in a year toda...,Depression,"[""so i was going through my stuff since i was ...","[[""5jPx8U"", 0.7506369352340698], [""3ng2N5"", 0...."